DROP TABLE IF EXISTS product;

CREATE TABLE product (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(30) NOT NULL,
  quantity INT DEFAULT NOT NULL,
  price NUMBER DEFAULT NOT NULL,
  version INT DEFAULT NOT NULL
);